version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresfe
    ports:
      - 5430:5432
    restart: always
    environment:
      - PGHOST=postgres
      - POSTGRES_PASSWORD=fe@2021
      - POSTGRES_DB=freshdb
    expose:
      - 5432



      
  backend:
    build: ./
    hostname: backend
    container_name: backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:fe@2021@postgres:5432/freshdb
    
networks:
  default:
    external : true
    name: webnet
    